version: '3.8'

services:
  php:
    image: php:8.1-apache
    volumes:
      - .:/var/www/html
    ports:
      - "8081:81"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
